#!/bin/bash

if [ $BLOCK_BUTTON -eq 1 ]
then
  if [ -e /tmp/ext-time ]
  then
    rm /tmp/ext-time
  else
    touch /tmp/ext-time
  fi
fi

if [ -e /tmp/ext-time ]
then
  echo '<span font="15" fgcolor="#009688" bgcolor="#03A9F4"> </span><span font="12" bgcolor="#009688">'$(date "+ %y/%m/%d")'</span><span font="15" fgcolor="#263238" bgcolor="#009688"> </span> '
else
  echo '<span font="15" fgcolor="#009688" bgcolor="#03A9F4"> </span><span font="12" bgcolor="#009688">'$(date "+ %I:%M %P")'</span><span font="15" fgcolor="#263238" bgcolor="#009688"> </span> '
fi
